---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mirror-agent
  namespace: cyber-riposte
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mirror-agent-log-reader
  namespace: cyber-riposte
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mirror-agent-log-reader
  namespace: cyber-riposte
subjects:
- kind: ServiceAccount
  name: mirror-agent
  namespace: cyber-riposte
roleRef:
  kind: Role
  name: mirror-agent-log-reader
  apiGroup: rbac.authorization.k8s.io
